/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CStudentinfo;
import Model.DBConnection;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Model.SStudentinfo;
import javax.swing.table.TableModel;
import java.util.regex.Matcher;
import java.util.regex.Pattern;



/**
 *
 * @author Thara
 */
public class Studentinfo extends javax.swing.JFrame {

    /**
     * Creates new form Studentinfo
     */
    public Studentinfo() {
        initComponents();
        show_Jtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public ArrayList<SStudentinfo> getStudentinfoList()
    {
        ArrayList<SStudentinfo> studentinfo = new ArrayList<SStudentinfo>();
        Connection con = DBConnection.connectDB();
        String query = "select * from studentinfo";
        Statement st;
        ResultSet rs;
        
        try
        {
            st = con.createStatement();
            rs =st.executeQuery(query);
            SStudentinfo studinfo;
            
            while(rs.next())
            {
                studinfo = new SStudentinfo(rs.getString("studid"),rs.getString("fname"),rs.getString("surname"),
                        rs.getString("dob"),rs.getString("gender"),rs.getString("email"),rs.getString("contact"),rs.getString("address"));
                studentinfo.add(studinfo);
            }
                
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return studentinfo;
    }
    
         public void show_Jtable()
    {
       ArrayList <SStudentinfo> list = getStudentinfoList();
        DefaultTableModel model = (DefaultTableModel)tableDark1.getModel();
        Object[] row = new Object[8];
        for(int i=0;i<list.size();i++)
        {
            row[0] = list.get(i).getStudid();
            row[1] = list.get(i).getFname();
            row[2] = list.get(i).getSurname();
            row[3] = list.get(i).getDob();
            row[4] = list.get(i).getGender();
            row[5] = list.get(i).getEmail();
            row[6] = list.get(i).getContact();
            row[7] = list.get(i).getAddress();

            
            model.addRow(row);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmb_gender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        btn_reset = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDark1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lbl_studid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(24, 81, 76, 20);

        txt_fname.setBackground(new java.awt.Color(182, 220, 228));
        txt_fname.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_fname.setForeground(new java.awt.Color(0, 0, 102));
        txt_fname.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(13, 73, 100), new java.awt.Color(169, 169, 186)));
        txt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnameActionPerformed(evt);
            }
        });
        txt_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_fnameKeyTyped(evt);
            }
        });
        getContentPane().add(txt_fname);
        txt_fname.setBounds(160, 70, 200, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Surname");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(24, 119, 76, 20);

        txt_surname.setBackground(new java.awt.Color(182, 220, 228));
        txt_surname.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_surname.setForeground(new java.awt.Color(0, 0, 102));
        txt_surname.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(13, 73, 100), new java.awt.Color(169, 169, 186)));
        txt_surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_surnameActionPerformed(evt);
            }
        });
        txt_surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_surnameKeyTyped(evt);
            }
        });
        getContentPane().add(txt_surname);
        txt_surname.setBounds(160, 110, 200, 32);

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Date of Birth");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(24, 157, 100, 20);

        txt_dob.setBackground(new java.awt.Color(182, 220, 228));
        txt_dob.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_dob.setForeground(new java.awt.Color(0, 0, 102));
        txt_dob.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(13, 73, 100), new java.awt.Color(169, 169, 186)));
        txt_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dobActionPerformed(evt);
            }
        });
        getContentPane().add(txt_dob);
        txt_dob.setBounds(160, 150, 200, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(24, 195, 76, 20);

        cmb_gender.setBackground(new java.awt.Color(182, 220, 228));
        cmb_gender.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        cmb_gender.setForeground(new java.awt.Color(0, 0, 102));
        cmb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cmb_gender.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(13, 73, 100), new java.awt.Color(169, 169, 186)));
        getContentPane().add(cmb_gender);
        cmb_gender.setBounds(160, 190, 200, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("E-mail");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(24, 233, 76, 20);

        txt_email.setBackground(new java.awt.Color(182, 220, 228));
        txt_email.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(0, 0, 102));
        txt_email.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(13, 73, 100), new java.awt.Color(169, 169, 186)));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emailKeyTyped(evt);
            }
        });
        getContentPane().add(txt_email);
        txt_email.setBounds(160, 230, 200, 32);

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Contact Number");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(24, 271, 110, 20);

        txt_contact.setBackground(new java.awt.Color(182, 220, 228));
        txt_contact.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_contact.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(13, 73, 100), new java.awt.Color(169, 169, 186)));
        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });
        getContentPane().add(txt_contact);
        txt_contact.setBounds(160, 270, 200, 32);

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Address");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 310, 80, 20);

        txt_address.setBackground(new java.awt.Color(182, 220, 228));
        txt_address.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_address.setForeground(new java.awt.Color(0, 0, 102));
        txt_address.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(13, 73, 100), new java.awt.Color(169, 169, 186)));
        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });
        getContentPane().add(txt_address);
        txt_address.setBounds(160, 310, 200, 66);

        btn_reset.setBackground(new java.awt.Color(13, 73, 100));
        btn_reset.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/account.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset);
        btn_reset.setBounds(210, 400, 120, 50);

        btn_update.setBackground(new java.awt.Color(13, 73, 100));
        btn_update.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/update icon.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update);
        btn_update.setBounds(70, 470, 120, 50);

        btn_add.setBackground(new java.awt.Color(13, 73, 100));
        btn_add.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Save-icon.png"))); // NOI18N
        btn_add.setText("Add Record");
        btn_add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add);
        btn_add.setBounds(70, 400, 120, 50);

        btn_delete.setBackground(new java.awt.Color(13, 73, 100));
        btn_delete.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/cancel1.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete);
        btn_delete.setBounds(210, 470, 120, 50);

        tableDark1.setBackground(new java.awt.Color(13, 73, 100));
        tableDark1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableDark1.setForeground(new java.awt.Color(255, 255, 255));
        tableDark1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "First Name", "Surname", "DOB", "Gender", "Email", "Phn No.", "Address"
            }
        ));
        tableDark1.setGridColor(new java.awt.Color(150, 200, 231));
        tableDark1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDark1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDark1);
        if (tableDark1.getColumnModel().getColumnCount() > 0) {
            tableDark1.getColumnModel().getColumn(7).setMinWidth(250);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(390, 50, 790, 490);

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("ID of the Student");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 40, 140, 20);
        getContentPane().add(lbl_studid);
        lbl_studid.setBounds(155, 39, 64, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/bk1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADD STUDENT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Microsoft JhengHei UI", 1, 24), new java.awt.Color(0, 36, 55))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 1240, 610);

        setSize(new java.awt.Dimension(1244, 616));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnameActionPerformed

    private void txt_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_surnameActionPerformed

    private void txt_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dobActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
     
        
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private static String generateNextId(String lastId) {
        int nextNumber = 1;
        if (lastId != null && lastId.startsWith("S")) {
            int lastNumber = Integer.parseInt(lastId.substring(1));
            nextNumber = lastNumber + 1;
        }
        
        String formattedNumber = String.format("%03d" , nextNumber);
        return "S" + formattedNumber;
    }
    
    private String generateLastID()
    {
        String lastId = null;
        try
        {
            ResultSet resultSet;
            CStudentinfo c2 = new CStudentinfo();
            resultSet = c2.getStudentInfo();
            
            if (resultSet.next()) {
                lastId = resultSet.getString(1);
            }

        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        return lastId;
    }
    
        
        
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        String studentid = generateNextId(generateLastID());
        String fname = txt_fname.getText();
        String surname = txt_surname.getText();
        String dob = txt_dob.getText();
        String gender = cmb_gender.getSelectedItem().toString();
        String email = txt_email.getText();
        String phn = txt_contact.getText();
        String address = txt_address.getText();
        String EMAIL_REGEX =
            "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
            
        
      if(!email.matches(EMAIL_REGEX))
      {
          JOptionPane.showMessageDialog(null, "Please enter a valid email !","INFO",JOptionPane.INFORMATION_MESSAGE);
      }
      
      else
        {
            if(studentid.isEmpty() || fname.isEmpty() || surname.isEmpty() 
                || dob.isEmpty() || email.isEmpty() || phn.isEmpty() || address.isEmpty())
              {
            JOptionPane.showMessageDialog(null, "Fill all Fields");
              }
            else
              {
            CStudentinfo stud = new CStudentinfo();
            stud.addStudent(studentid, fname, surname, dob, gender, email, phn, address);
            
            DefaultTableModel model = (DefaultTableModel)tableDark1.getModel();
            model.setRowCount(0);
            show_Jtable();  
               }
        }
        
        

        

    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String studentid = lbl_studid.getText();
        String fname = txt_fname.getText();
        String surname = txt_surname.getText();
        String dob = txt_dob.getText();
        String gender = cmb_gender.getSelectedItem().toString();
        String email = txt_email.getText();
        String phn = txt_contact.getText();
        String address = txt_address.getText();
        
        CStudentinfo c1 = new CStudentinfo();
        c1.updateStudent(studentid,fname,surname,dob,gender,email,phn,address);
        
         DefaultTableModel model = (DefaultTableModel)tableDark1.getModel();
            model.setRowCount(0);
            show_Jtable();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        String studentid = lbl_studid.getText();
        String fname = txt_fname.getText();
        String surname = txt_surname.getText();
        String dob = txt_dob.getText();
        
        String email = txt_email.getText();
        String phn = txt_contact.getText();
        String address = txt_address.getText();
        
        CStudentinfo c1 = new CStudentinfo();
        c1.deleteStudent(studentid, fname, surname, dob, email, phn, address);
        
        lbl_studid.setText(null);
        txt_fname.setText(null);
        txt_surname.setText(null);
        txt_dob.setText(null);
        txt_email.setText(null);
        txt_contact.setText(null);
        txt_address.setText(null);
        
         DefaultTableModel model = (DefaultTableModel)tableDark1.getModel();
            model.setRowCount(0);
            show_Jtable();

    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tableDark1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDark1MouseClicked
        // TODO add your handling code here:
        
        int i = tableDark1.getSelectedRow();
        TableModel model = tableDark1.getModel();
        lbl_studid.setText(model.getValueAt(i, 0).toString());
        txt_fname.setText(model.getValueAt(i, 1).toString());
        txt_surname.setText(model.getValueAt(i, 2).toString());
        txt_dob.setText(model.getValueAt(i, 3).toString());
        txt_email.setText(model.getValueAt(i, 5).toString());
        txt_contact.setText(model.getValueAt(i, 6).toString());
        txt_address.setText(model.getValueAt(i, 7).toString());
        String combosub = model.getValueAt(i,4).toString();
        
        for(i=0;i<cmb_gender.getItemCount();i++)
        {
            if(cmb_gender.getItemAt(i).toString().equalsIgnoreCase(combosub))
            {
               cmb_gender.setSelectedIndex(i);
            }
        }
        

                
        
    }//GEN-LAST:event_tableDark1MouseClicked

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        
        lbl_studid.setText(null);
        txt_fname.setText(null);
        txt_surname.setText(null);
        txt_dob.setText(null);
        txt_email.setText(null);
        txt_contact.setText(null);
        txt_address.setText(null);

    }//GEN-LAST:event_btn_resetActionPerformed

    private void txt_fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fnameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
    
    if (!Character.isLetter(c)) {
        evt.consume(); 
    }
    }//GEN-LAST:event_txt_fnameKeyTyped

    private void txt_surnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_surnameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
    
    if (!Character.isLetter(c)) {
        evt.consume(); // Consume the event, i.e., prevent the character from being typed
    }
    }//GEN-LAST:event_txt_surnameKeyTyped

    
    private void txt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyTyped
        
    }//GEN-LAST:event_txt_emailKeyTyped

    
    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SStudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SStudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SStudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SStudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studentinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_studid;
    private javax.swing.JTable tableDark1;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables
}
