/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import Control.CMarks;
import Control.CSubject;
import java.awt.Font;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Thara
 */
public class VASMarks extends javax.swing.JFrame {

    /**
     * Creates new form VSMarks
     */
    public VASMarks() {
        initComponents();
        populateStudentNames();
        populateSubjectNames();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmb_stdname = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        btn_submit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_marks = new javax.swing.JTextField();
        lbl_grade = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Student ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 70, 100, 20);

        cmb_stdname.setBackground(new java.awt.Color(61, 147, 225));
        cmb_stdname.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        cmb_stdname.setForeground(new java.awt.Color(0, 0, 51));
        cmb_stdname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_stdname.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(13, 73, 100), new java.awt.Color(169, 169, 186)));
        cmb_stdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_stdnameActionPerformed(evt);
            }
        });
        cmb_stdname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmb_stdnameKeyTyped(evt);
            }
        });
        getContentPane().add(cmb_stdname);
        cmb_stdname.setBounds(200, 60, 190, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Subject Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 120, 93, 16);

        jComboBox2.setBackground(new java.awt.Color(61, 147, 225));
        jComboBox2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 0, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(13, 73, 100), new java.awt.Color(169, 169, 186)));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(200, 110, 190, 30);

        btn_submit.setBackground(new java.awt.Color(13, 73, 100));
        btn_submit.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/submit.png"))); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_submit);
        btn_submit.setBounds(180, 230, 131, 39);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(451, 321, 0, 0);

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Marks");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 170, 61, 16);

        txt_marks.setBackground(new java.awt.Color(186, 216, 228));
        txt_marks.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_marks.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(13, 73, 100), new java.awt.Color(169, 169, 186)));
        txt_marks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_marksKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_marksKeyTyped(evt);
            }
        });
        getContentPane().add(txt_marks);
        txt_marks.setBounds(200, 160, 70, 30);

        lbl_grade.setBackground(new java.awt.Color(204, 204, 255));
        lbl_grade.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbl_grade.setForeground(new java.awt.Color(0, 0, 0));
        lbl_grade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_gradeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_gradeKeyReleased(evt);
            }
        });
        getContentPane().add(lbl_grade);
        lbl_grade.setBounds(280, 160, 110, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/bk7.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADD STUDENT MARKS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Historic", 1, 18), new java.awt.Color(0, 32, 44))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-40, 0, 530, 340);

        setSize(new java.awt.Dimension(483, 334));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_marksKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_marksKeyTyped
           char c = evt.getKeyChar();

    // Check if the entered character is a digit or backspace
    if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
        evt.consume(); // Ignore non-digit characters
        return;
    }

    // Check the resulting text value
    String currentText = txt_marks.getText();
    if (!currentText.isEmpty() || c != KeyEvent.VK_BACK_SPACE) {
        currentText += c;
    }

    try {
        int value = Integer.parseInt(currentText);

        // Check if the resulting number is between 1 and 100
        if (value < 1 || value > 100) {
            evt.consume(); // Ignore values outside the desired range
        }
    } catch (NumberFormatException e) {
        evt.consume(); // Ignore invalid integer input
    }
    }//GEN-LAST:event_txt_marksKeyTyped

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
                 
        String StdID = (String)cmb_stdname.getSelectedItem();
        String sub_ID = (String) jComboBox2.getSelectedItem();
        Double marks = Double.parseDouble(txt_marks.getText());
        String grade = lbl_grade.getText();

        CMarks c1 = new CMarks();
        c1.addMarks(StdID, sub_ID, marks , grade);

    }//GEN-LAST:event_btn_submitActionPerformed

    private void lbl_gradeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_gradeKeyReleased
       
    }//GEN-LAST:event_lbl_gradeKeyReleased

    private void lbl_gradeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_gradeKeyPressed
        
    }//GEN-LAST:event_lbl_gradeKeyPressed

    private void txt_marksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_marksKeyPressed
        String marksText = txt_marks.getText();

        try {
        int marks = Integer.parseInt(marksText);

        String grade;
        if (marks < 40 && marks >0) {
            grade = "F";
        } else if (marks < 55 && marks >=40) {
            grade = "S";
        } else if (marks < 65 && marks >=55) {
            grade = "C";
        } else if (marks < 75 && marks >=65) {
            grade = "B";
        } else {
            grade = "A";
        }

        lbl_grade.setText(grade);

    } catch (NumberFormatException e) {
        // Handle the case where the input is not a valid integer
        lbl_grade.setText("Invalid input");
    }
    }//GEN-LAST:event_txt_marksKeyPressed

    private void cmb_stdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_stdnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_stdnameActionPerformed

    private void cmb_stdnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_stdnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_stdnameKeyTyped

    private void populateStudentNames() {
        // Establish a database connection
        ResultSet rt = null;
        try
        {
            Statement st = Model.DBConnection.connectDB().createStatement();
            rt =  st.executeQuery("SELECT studid FROM studentinfo;");
            
            ArrayList<String> studentNames = new ArrayList<>();
            while (rt.next()) {
                studentNames.add(rt.getString("studid"));
            }
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(studentNames.toArray(new String[0]));
            cmb_stdname.setModel(model);
            
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    private void populateSubjectNames() {
        // Establish a database connection
        ResultSet rt = null;
        try
        {
            Statement st = Model.DBConnection.connectDB().createStatement();
            rt =  st.executeQuery("SELECT subName FROM subject;");
            
            ArrayList<String> subjectNames = new ArrayList<>();
            while (rt.next()) {
                subjectNames.add(rt.getString("subname"));
            }
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(subjectNames.toArray(new String[0]));
            jComboBox2.setModel(model);
            
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VASMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VASMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VASMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VASMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VASMarks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> cmb_stdname;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_grade;
    private javax.swing.JTextField txt_marks;
    // End of variables declaration//GEN-END:variables
}
