/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CSubject;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Thara
 */
public class VHome extends javax.swing.JFrame {

    /**
     * Creates new form VHome
     */
private DefaultTableModel tableModel;
private ResultSet rst;
    public VHome() {
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btn_subinfo = new javax.swing.JButton();
        btn_addmarks = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_marks = new javax.swing.JTable();
        btn_report = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(13, 73, 100));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View Student info");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 330, 200, 40);

        btn_subinfo.setBackground(new java.awt.Color(13, 73, 100));
        btn_subinfo.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btn_subinfo.setForeground(new java.awt.Color(255, 255, 255));
        btn_subinfo.setText("View Subject Info");
        btn_subinfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        btn_subinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subinfoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_subinfo);
        btn_subinfo.setBounds(40, 270, 200, 40);

        btn_addmarks.setBackground(new java.awt.Color(13, 73, 100));
        btn_addmarks.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btn_addmarks.setForeground(new java.awt.Color(255, 255, 255));
        btn_addmarks.setText("Add Marks");
        btn_addmarks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        btn_addmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addmarksActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addmarks);
        btn_addmarks.setBounds(40, 210, 200, 40);

        tbl_marks.setBackground(new java.awt.Color(6, 49, 91));
        tbl_marks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tbl_marks.setForeground(new java.awt.Color(255, 255, 255));
        tbl_marks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_marks);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(360, 110, 560, 410);

        btn_report.setBackground(new java.awt.Color(13, 73, 100));
        btn_report.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btn_report.setForeground(new java.awt.Color(255, 255, 255));
        btn_report.setText("REPORT");
        btn_report.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });
        getContentPane().add(btn_report);
        btn_report.setBounds(40, 450, 200, 40);

        jButton2.setBackground(new java.awt.Color(13, 73, 100));
        jButton2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VIew Student Marks");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 390, 200, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/bk9.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, -10, 724, 670);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logo.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 30, 130, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/regp12.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, 0, 310, 590);

        setBounds(0, 0, 1013, 579);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Studentinfo s1 = new Studentinfo();
        s1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_subinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subinfoActionPerformed
        Vsubjectinfo v1 = new Vsubjectinfo();
        v1.setVisible(true);
    }//GEN-LAST:event_btn_subinfoActionPerformed

    private void setupUI()
    {
        String[] columnNames = {"Student ID , Student Name , No of Subjects , Total Marks , Average Marks"};
        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(columnNames);
        tbl_marks.setModel(tableModel);
       
    }
     
    private void populateTable() {
        // Create the table model
        DefaultTableModel model = new DefaultTableModel();
        tbl_marks.setModel(model);

        // Add columns to the model
        model.addColumn("Student ID");
        model.addColumn("Student Name");
        model.addColumn("Number of Subjects");
        model.addColumn("Total Marks");
        model.addColumn("Average Marks");

        
        
        ResultSet rt = null;
        // Execute the SQL query
        try {
             Statement st = Model.DBConnection.connectDB().createStatement();
             rt  = st.executeQuery("SELECT s.studid AS StudentID, CONCAT(s.fname, ' ', s.surname) AS StudentName, COUNT(m.SubName) AS NumberOfSubjects, SUM(m.Marks) AS TotalMarks, AVG(m.Marks) AS AverageMarks FROM studentinfo s JOIN marks m ON s.studid = m.StudentID GROUP BY s.studid, s.fname, s.surname");

            // Iterate through the result set and add rows to the model
            while (rt.next()) {
                Object[] row = {
                        rt.getString("StudentID"),
                        rt.getString("StudentName"),
                        rt.getInt("NumberOfSubjects"),
                        rt.getDouble("TotalMarks"),
                        rt.getDouble("AverageMarks")
                };
                model.addRow(row);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            // Handle any exceptions or show an error message
        }
        catch (Exception e) {
            e.printStackTrace();
            // Handle any exceptions or show an error message
        }

        // Set the model to the JTable
        tbl_marks.setModel(model);
    }
    
    private void btn_addmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addmarksActionPerformed
        VASMarks v2 = new VASMarks();
        v2.setVisible(true);
    }//GEN-LAST:event_btn_addmarksActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
         try
        {
            DBConnection.connectDB();
            JasperDesign jasDesign = JRXmlLoader.load("C:\\Users\\Thara\\Documents\\NetBeansProjects\\Student_Management\\src\\View\\eadreport.jrxml");
            JRDesignQuery desquery = new JRDesignQuery();   
            String sqlquery = " SELECT s.studid AS StudentID, CONCAT(s.fname, ' ', s.surname) AS StudentName, COUNT(m.SubName) AS NumberOfSubjects, SUM(m.Marks) AS TotalMarks, AVG(m.Marks) AS AverageMarks FROM studentinfo s JOIN marks m ON s.studid = m.StudentID GROUP BY s.studid, s.fname, s.surname ORDER BY TotalMarks DESC;";
            desquery.setText(sqlquery);
            jasDesign.setQuery(desquery);
            
            JasperReport jasreport = JasperCompileManager.compileReport(jasDesign);
            JasperPrint jasprint = JasperFillManager.fillReport(jasreport,null,DBConnection.connectDB());
            JasperViewer.viewReport(jasprint,false);
        
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_reportActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addmarks;
    private javax.swing.JButton btn_report;
    private javax.swing.JButton btn_subinfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_marks;
    // End of variables declaration//GEN-END:variables
}
