/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CMarks;
import Control.CSubject;
import Control.CSMarks;
import Model.DBConnection;
import Model.SSMarks;
import static com.lowagie.text.ElementTags.ID;

import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Thara
 */
public class VSMarks extends javax.swing.JFrame {

    /**
     * Creates new form VSMarks
     */
   private DefaultTableModel tableMode2;
   private ResultSet rst;

    public VSMarks() {
        initComponents();
        setupUI();
        populateStudentID();
       // String StudentID = (String) cb_Id.getSelectedItem();
        populateTable("");
    }
     private void setupUI()
    {
        String[] columnNames = {"Subject Name,Marks,Grade"};
        tableMode2 = new DefaultTableModel();
        tableMode2.setColumnIdentifiers(columnNames);
        tbl_1.setModel(tableMode2);
       
    }
     
     
     
    private void populateTable(String StudentID) {
        DefaultTableModel model = new DefaultTableModel();
        tbl_1.setModel(model);

        // Add columns to the model
        model.addColumn("Subject Name");
        model.addColumn("Marks");
        model.addColumn("Grade");
        
         ResultSet rt = null;
        // Execute the SQL query
        try {
             Statement st = Model.DBConnection.connectDB().createStatement();
             rt  = st.executeQuery("SELECT m.* from marks m WHERE m.StudentID='"+StudentID+"'");
             

            // Iterate through the result set and add rows to the model
            while (rt.next()) {
                Object[] row = {
                        rt.getString("SubName"),
                        rt.getDouble("Marks"),
                        rt.getString("Grade")
                };
                //System.out.println("hai");
                model.addRow(row);
            }
            //System.out.println(model.getRowCount());
            //System.out.println("hello");
        } catch (SQLException e) {
            e.printStackTrace();
            // Handle any exceptions or show an error message
        }
        catch (Exception e) {
            e.printStackTrace();
            // Handle any exceptions or show an error message
        }
         tbl_1.setModel(model);
      
         // Create a font with the desired size
    Font tableFont = new Font("Segoe UI", Font.PLAIN, 36); // Change the font and size as needed

    // Create a cell renderer with the new font
    DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
    cellRenderer.setFont(tableFont);

    // Apply the cell renderer to all columns
    for (int columnIndex = 0; columnIndex < tableMode2.getColumnCount(); columnIndex++) {
        tbl_1.getColumnModel().getColumn(columnIndex).setCellRenderer(cellRenderer);
    }
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_Id = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_1 = new javax.swing.JTable();
        btn_show = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Student ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 70, 69, 16);

        cb_Id.setBackground(new java.awt.Color(230, 230, 245));
        cb_Id.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        cb_Id.setForeground(new java.awt.Color(0, 0, 102));
        cb_Id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_IdActionPerformed(evt);
            }
        });
        getContentPane().add(cb_Id);
        cb_Id.setBounds(210, 60, 150, 30);

        tbl_1.setBackground(new java.awt.Color(13, 73, 100));
        tbl_1.setForeground(new java.awt.Color(255, 255, 255));
        tbl_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Subject Name", "Marks", "Grade"
            }
        ));
        tbl_1.setShowGrid(false);
        jScrollPane1.setViewportView(tbl_1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 110, 494, 308);

        btn_show.setBackground(new java.awt.Color(13, 73, 100));
        btn_show.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btn_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/loupe.png"))); // NOI18N
        btn_show.setText("Show");
        btn_show.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        btn_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showActionPerformed(evt);
            }
        });
        getContentPane().add(btn_show);
        btn_show.setBounds(430, 50, 100, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/bk8.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SHOW STUDENT MARKS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 1, 18), new java.awt.Color(0, 47, 68))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 630, 510);

        setSize(new java.awt.Dimension(629, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showActionPerformed
             
         String StudentID = (String) cb_Id.getSelectedItem();
         System.out.println("hai");
         System.out.println(StudentID);
         populateTable(StudentID);
    }//GEN-LAST:event_btn_showActionPerformed

    private void cb_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_IdActionPerformed

     private void populateStudentID() {
        // Establish a database connection
        ResultSet rt = null;
        try
        {
            Statement st = Model.DBConnection.connectDB().createStatement();
            rt =  st.executeQuery("SELECT s.studid FROM studentinfo s;");
            
            ArrayList<String> studentID = new ArrayList<>();
            while (rt.next()) {
                studentID.add(rt.getString("studid"));
            }
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(studentID.toArray(new String[0]));
            cb_Id.setModel(model);
            
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VSMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VSMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VSMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VSMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VSMarks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_show;
    private javax.swing.JComboBox<String> cb_Id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_1;
    // End of variables declaration//GEN-END:variables

    private static class c1 {

              
        public c1() {
        }
    }

    
  

    

   

   
}
